name: Fetch Secrets from AKV

description: Fetches value and file secrets from AKV

inputs:
  vault-name:
    description: The name of the AKV to query
    required: true
  value-secrets:
    description: Newline delimited list of secret names for value secrets
    required: false
  file-secrets:
    description: Newline delimited list of "secret name, output file name" rows
    required: false

outputs:
  fetched-secrets:
    description: An object containing the key value pairs of fetched value secrets. Keys are camelCased variant of value-secrets[n].
    value: ${{ steps.fetch-value-secrets.outputs.json }}

runs:
  using: "composite"
  steps:
    - name: Fetch Value Secrets
      id: fetch-value-secrets
      shell: bash
      env:
        VAULT_NAME: ${{ inputs.vault-name }}
        VALUE_SECRETS: ${{ inputs.value-secrets }}
      run: |
        fetch() { az keyvault secret show --vault-name "$VAULT_NAME" --name "$1" --query value -o tsv; }

        kebabToCamel() { echo "$1" | sed 's/-\([a-z]\)/\U\1/g'; }

        JSON="{}"

        readarray -t SECRET_NAMES_ARRAY <<< "$VALUE_SECRETS"
        for NAME in "${SECRET_NAMES_ARRAY[@]}"; do
          NAME=$(echo "$NAME" | sed 's/[[:space:]]//g')

          [ "${#NAME}" -eq 0 ] && continue

          VALUE=$(fetch "$NAME")
          while IFS= read -r _line; do
            [ -n "$_line" ] && echo "::add-mask::$_line"
          done <<< "$VALUE"

          CAMEL_NAME=$(kebabToCamel "${NAME,,}")
          JSON=$(echo "$JSON" | jq -c --arg k "$CAMEL_NAME" --arg v "$VALUE" '. + {($k): $v}')
        done

        echo "::add-mask::$JSON"

        {
          echo "json<<__EOF__"
          echo "$JSON"
          echo "__EOF__"
        } >> "$GITHUB_OUTPUT"

    - name: Fetch File Secrets
      shell: bash
      run: |
        fetch() { az keyvault secret show --vault-name "${{ inputs.vault-name }}" --name "$1" --query value -o tsv; }

        SECRET_NAMES="${{ inputs.file-secrets }}"
        readarray -t SECRET_NAMES_ARRAY <<< "$SECRET_NAMES"
        for KEY_FILE in "${SECRET_NAMES_ARRAY[@]}"; do
          KEY=$(echo "$KEY_FILE" | awk -F',' '{ print $1; }')
          FILE=$(echo "$KEY_FILE" | awk -F',' '{ print $2; }')
          SECRET=$(fetch "$KEY")
          echo "::add-mask::$SECRET"
          mkdir -p "$(dirname "$FILE")"
          echo "$SECRET" > "$FILE"
        done
