logging:
  structured:
    format:
      console: json

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when-authorized
  info:
    env:
      enabled: true
    build:
      enabled: true

spring:
  application:
    name: coinservice
  config:
    import: azureAppConfiguration
  cloud:
    azure:
      credential:
        client-id: ${AZURE_CLIENT_ID:}
        client-secret: ${AZURE_CLIENT_SECRET:}
      profile:
        tenant-id: b576cc51-2a06-4b5b-a53b-b64f0780d721
      appconfiguration:
        stores:
          - endpoint: https://ac-coinservice.azconfig.io
