logging:
  structured:
    format:
      console: logstash

management:
  server:
    port: 8081
    address: 127.0.0.1
    ssl:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers, prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when-authorized
    prometheus:
      enabled: true
  info:
    env:
      enabled: true
    build:
      enabled: true

# TODO: Add to AZ App Configuration
# beemer:
#   siwe:
#     domain: ""
#     uri: ""
#     issuer: ""

spring:
  application:
    name: coinservice
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sts.windows.net/${spring.cloud.azure.profile.tenant-id}/
  config:
    import: azureAppConfiguration
  cloud:
    azure:
      credential:
        client-id: ${AZURE_CLIENT_ID:}
        client-secret: ${AZURE_CLIENT_SECRET:}
      profile:
        tenant-id: b576cc51-2a06-4b5b-a53b-b64f0780d721
      appconfiguration:
        stores:
          - endpoint: https://ac-coinservice.azconfig.io
