beemer:
  siwe:
    domain: localhost
    uri: https://localhost:4200
    issuer: https://localhost:8443

logging:
  level:
      com.beemer.coinservice.chaintask.epoch.CreateEpoch: trace
  structured:
    format:
      console:


server:
  port: 8443
  ssl:
    bundle: coinservice

spring:
  ssl:
    bundle:
      pem:
        coinservice:
          keystore:
            certificate: file:local-ssl/localhost.pem
            private-key: file:local-ssl/localhost-key.pem
